// ═══════════════════════════════════════════════════════════════════════════════
// SHIELD SERVICE TYPES
// ═══════════════════════════════════════════════════════════════════════════════

export type ShieldAction = 'skip' | 'warn' | 'crisis';

/**
 * Risk assessment generated by LLM
 * Expert-level, specific analysis (not generic warnings)
 */
export interface RiskAssessment {
  /** Domain of risk: financial, career, legal, health, relationship, other */
  domain: string;
  
  /** Specific risk explanation - what could actually go wrong */
  riskExplanation: string;
  
  /** Real consequences that could happen (2-3 items) */
  consequences: string[];
  
  /** Practical alternatives to consider (2-3 items) */
  alternatives: string[];
  
  /** Reflective question to prompt pause and thought */
  question: string;
}

/**
 * Result of shield evaluation
 */
export interface ShieldEvaluation {
  action: ShieldAction;
  safetySignal: 'none' | 'low' | 'medium' | 'high';
  urgency: 'low' | 'medium' | 'high';
  
  /** Risk assessment from LLM (only for medium/high) */
  riskAssessment?: RiskAssessment;
  
  /** Short 2-3 sentence warning message (only for medium) */
  warningMessage?: string;
  
  /** Crisis session ID (only for high) */
  sessionId?: string;
  
  /** Activation ID for audit trail */
  activationId?: string;
}

/**
 * Crisis session record (for high signals)
 */
export interface CrisisSession {
  id: string;
  userId: string;
  activationId: string;
  status: 'active' | 'resolved';
  createdAt: Date;
  resolvedAt?: Date;
}

/**
 * Shield activation record (audit)
 */
export interface ShieldActivation {
  id: string;
  userId: string;
  safetySignal: string;
  urgency: string;
  triggerMessage: string;
  riskAssessment?: RiskAssessment;
  actionTaken: 'warning' | 'crisis';
  resolvedAt?: Date;
  createdAt: Date;
}

/**
 * Pending message stored in Redis for MEDIUM signals
 * User must confirm warning before message is processed
 */
export interface PendingMessage {
  activationId: string;
  userId: string;
  message: string;
  conversationId: string;
  timestamp: number;
}
